// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _AIS_DimensionLayoutMode_HeaderFile
#define _AIS_DimensionLayoutMode_HeaderFile

//! Specifies dimension layout mode: how text and dimension line <br>
//! will be placed. <br>
//! If DLM_Automatic mode is chosen text will be aligned automatically <br>
//! and centered if it is placed not on the extensions. <br>
//! If DLM_Manual mode is chosen text position will not been centered <br>
//! and is placed just where its position is set by user. <br>
enum AIS_DimensionLayoutMode {
AIS_DLM_Automatic,
AIS_DLM_Manual
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
